services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  
    networks:
      - app-network

  app:
    build: .
    container_name: flask_app
    command: celery -A app.tasks worker --loglevel=info  
    volumes:
      - .:/app
    ports:
      - "5000:5000"  
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

  web:
    build: .
    container_name: flask_web
    command: flask run --host=0.0.0.0 --port=5000  
    volumes:
      - .:/app
    ports:
      - "5001:5000"  
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge